[package]
name = "teleapi"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
rouille = "3.6.2"
serde = "1.0.203"
serde_derive = "1.0.203"
serde_yaml = "0.9.34"
